import bash from "highlight.js/lib/languages/bash";
import c from "highlight.js/lib/languages/c";
import cpp from "highlight.js/lib/languages/cpp";
import csharp from "highlight.js/lib/languages/csharp";
import css from "highlight.js/lib/languages/css";
import dart from "highlight.js/lib/languages/dart";
import dockerfile from "highlight.js/lib/languages/dockerfile";
import elixir from "highlight.js/lib/languages/elixir";
import go from "highlight.js/lib/languages/go";
import java from "highlight.js/lib/languages/java";
import javascript from "highlight.js/lib/languages/javascript";
import json from "highlight.js/lib/languages/json";
import kotlin from "highlight.js/lib/languages/kotlin";
import lua from "highlight.js/lib/languages/lua";
import makefile from "highlight.js/lib/languages/makefile";
import markdown from "highlight.js/lib/languages/markdown";
import perl from "highlight.js/lib/languages/perl";
import php from "highlight.js/lib/languages/php";
import python from "highlight.js/lib/languages/python";
import ruby from "highlight.js/lib/languages/ruby";
import rust from "highlight.js/lib/languages/rust";
import sql from "highlight.js/lib/languages/sql";
import swift from "highlight.js/lib/languages/swift";
import typescript from "highlight.js/lib/languages/typescript";
import xml from "highlight.js/lib/languages/xml";
import yaml from "highlight.js/lib/languages/yaml";
import { createLowlight } from "lowlight";

const lowlight = createLowlight();

lowlight.register("bash", bash);
lowlight.register("c", c);
lowlight.register("cpp", cpp);
lowlight.register("csharp", csharp);
lowlight.register("css", css);
lowlight.register("dart", dart);
lowlight.register("dockerfile", dockerfile);
lowlight.register("elixir", elixir);
lowlight.register("go", go);
lowlight.register("html", xml);
lowlight.register("java", java);
lowlight.register("javascript", javascript);
lowlight.register("json", json);
lowlight.register("kotlin", kotlin);
lowlight.register("lua", lua);
lowlight.register("makefile", makefile);
lowlight.register("markdown", markdown);
lowlight.register("perl", perl);
lowlight.register("php", php);
lowlight.register("python", python);
lowlight.register("ruby", ruby);
lowlight.register("rust", rust);
lowlight.register("sql", sql);
lowlight.register("swift", swift);
lowlight.register("typescript", typescript);
lowlight.register("xml", xml);
lowlight.register("yaml", yaml);

lowlight.register("psql", sql);

export { lowlight };
